server:
  port : 8282
  max-http-header-size: 30000
  timezone: ${SERVER_TIMEZONE:IST}
  servlet:
    context-path: /lens

  compression:
    enabled: true
    mime-types: application/json

spring:
  application:
    name: Lens
